if(ANDROID)
    set(JSONCPP_INCLUDE_DIR
        ${THIRD_PARTY_JSONCPP_DIR}/${ANDROID_ABI}/include)
    set(JSONCPP_LIBRARY
        ${THIRD_PARTY_JSONCPP_DIR}/${ANDROID_ABI}/lib/libjsoncpp.a)
endif()

find_package(JsonCpp REQUIRED)

set(MBP_JSONCPP_INCLUDES ${JSONCPP_INCLUDE_DIR})
set(MBP_JSONCPP_LIBRARIES ${JSONCPP_LIBRARIES})
